language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- yarn run lint
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "Ay0FVzATpmowNXoQKOGpLGBKPMtdTLpxWxSbPtIK8B/J/xqGK5BSoiiuoHxPVhlcns740PNNMHWGxuIV83ar+doYzF6rFw+fDCb6Nc1OssBk1jjSyTANi1l/eOi+Ko4MuT11eaATmHb5wu3NZELvcBH+9PmyiuSbtIIgsZ7puSCEMVCQpUqNHyi96L0yotQxUp7Kqjk3HKaYRr8mByzq/+BYoyn5WvheVec5whgGs7Avt+JHP5ofMcMe/R5ieZcCAHsHVIU07OzUMleGnYwM2Z9dGjx89rRwRNpwbvgqYxdOP3lYsuU7Po/fc5lHhAzs6CFdYEzjohnlMlWnaOMJf+7R6/neL+uQWBEpwHmkFMc+TPBOx9yUmYEVyNGEkDdEOGL+YUPAPNoJqpoUlDLSabeWZPDL0evrmC9L5BwyNJzwZ9CK5U7CmvssR5vxOFZMApFgCSnhoRDhLDwyO6l2cRcC4HgQHe+sUFsuJwEXh8r5e/e2l6OI0pY6ohVhCwbksMfc1IHz1+gA3isz8DO6td9vMrTM9YOp4kibjVLatssi9GWdxwOeQpbUD9g9a/gf72d8F9Snqg5LjKfQgLGxt/8LK2PcShho2WBWOhgXEd0k0Ew2wMndCXtAGKa+pwYr0cJ4wrImV1nR//1ioop19wCKhTVvg39dgtUJmZlZj2I="
  app: state-local-storage
  on:
    repo: alpersonalwebsite/state-local-storage