language: node_js
node_js:
- node
sudo: false
install: yarn install
script:
- yarn run lint
- echo "skipping tests"
deploy:
  provider: heroku
  api_key:
    secure: "PEPb0Vso28bG/VVuXu1aukBq3ntcRg5DKT4ubOwmOHLhBfiK1sJ693U82HbEdzhywSn1es6lIiyb0iuEUUC+uu1cFEnEySC6Vf2pKAsVWV/E0rNdAonZoWz6b6q1rb3URF3VBSIunUrNaJgVRFf7Ua1sAobizyJi+u7rOHQUjCUlqpAn/M6sVbzQrzz2tz4jE9RTLSeC+EMN1fCI/s563n/51XqbhvobwDF7NYzPkvJvLB3BGxmuhUju0eU0f5B0SxDT+atSawdaRNoFcNh4ueL8+sggbM0B0lrAp+ATJO7OpA4Mr5uSXMRqOYg3jBfJ29nuFyI5o+BtCWuP0uD2PqY7wr646cvmrjrXB0fo79EltuLeDdC+tQeA0xt1Gfu4esJUqty0T9+99n+4OXX1HzRtI/roHS0hrgwVOwppYP8CT62JicZCuV1Al0PgcP/kCQVFwsrgzAliyqFK4ndmY5MggHTqw2k/s8M2qMnbd8B9mEgkviQaRbERloNW9L3MEUqmDgDqb4/OXxeLkzy/kYaHSv4nLO7s9O4FzoLvah1e3YbkEWEGCYlZkhHJKS6geChkgdzONEpsCpaCYdngIwbfPHLp757eX7lPWTPuYENoeXFGQHgvNIUf9kF383hRnMHaTlkYx/Js6cizx/vJYkRE0ewAEeybISFDpXT3lZQ="
  app: react-state-local-storage
  on:
    repo: alpersonalwebsite/react-state-local-storage